name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      # - name: "Repository Meta"
      #   uses: varunsridharan/action-repository-meta@main
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update README.md
        run: |
          sed -i 's/<reponame>/'${{ github.event.repository.name }}'/' README.md
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env: 
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
